import { FormEvent, useEffect, useState, type ComponentType } from 'react'
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bell, Check, ChevronDown, Command, Crown, FileText, Globe2, Hammer, KeyRound, LayoutDashboard, Lock, LogOut, Menu, Palette, Plus, Radar, RefreshCw, Search, Server, Settings, Shield, ShieldAlert, ShieldCheck, Sparkles, Ticket, Trash2, UserRound, Users, X, Zap } from 'lucide-react'

type ServerItem={id:string;name:string;icon:string;members:number;channels:number;roles:number;owner:boolean;online:boolean}
type User={username:string;discord_username:string}
type Toast={message:string;kind:'success'|'error'|'info'}
type Mod={id:string;label:string;icon:ComponentType<{size?:number}>;group:string;description:string}
const mods:Mod[]=[
{id:'overview',label:'Overview',icon:LayoutDashboard,group:'Control',description:'Live server overview and RM health.'},
{id:'moderation',label:'Moderation',icon:Hammer,group:'Protection',description:'Warnings, timeouts, kicks, bans and case defaults.'},
{id:'automod',label:'AutoMod',icon:ShieldCheck,group:'Protection',description:'Spam, links, mentions and message protection.'},
{id:'anti-raid',label:'Anti-Raid',icon:Radar,group:'Protection',description:'Join velocity, account age and raid mode.'},
{id:'anti-nuke',label:'Anti-Nuke',icon:ShieldAlert,group:'Protection',description:'Protect channels, roles and server permissions.'},
{id:'security',label:'Security Center',icon:Shield,group:'Protection',description:'Unified protection posture and trusted controls.'},
{id:'wordfilter',label:'Word Filter',icon:AlertTriangle,group:'Protection',description:'Blocked words and automated responses.'},
{id:'logs',label:'Logs',icon:FileText,group:'Management',description:'Audit events and security logging.'},
{id:'tickets',label:'Tickets',icon:Ticket,group:'Management',description:'Ticket routing and support defaults.'},
{id:'welcome',label:'Welcome',icon:Sparkles,group:'Management',description:'Welcome and onboarding automation.'},
{id:'reaction-roles',label:'Reaction Roles',icon:Users,group:'Management',description:'Self-assignable roles and onboarding.'},
{id:'custom-commands',label:'Custom Commands',icon:Command,group:'Management',description:'Create your own rm! commands.'},
{id:'auto-responders',label:'Auto Responders',icon:Zap,group:'Management',description:'Keyword and phrase automation.'},
{id:'economy',label:'Economy',icon:BarChart3,group:'Community',description:'Currency, rewards and shop settings.'},
{id:'levels',label:'Levels',icon:Zap,group:'Community',description:'XP and leveling configuration.'},
{id:'permissions',label:'Permissions',icon:KeyRound,group:'Access',description:'Owner and dashboard safety policies.'},
{id:'trust',label:'Trust',icon:Crown,group:'Access',description:'Trusted operators and protected IDs.'},
{id:'server-config',label:'Server Config',icon:Server,group:'Customization',description:'Prefix, locale and command behavior.'},
{id:'appearance',label:'Appearance',icon:Palette,group:'Customization',description:'Brand accent, glass mode and layout.'},
{id:'integrations',label:'Integrations',icon:Globe2,group:'Customization',description:'External service and webhook switches.'},
{id:'bot-settings',label:'Bot Settings',icon:Settings,group:'Customization',description:'Presence, behavior and global settings.'},
]
function cn(...x:Array<string|false|undefined>){return x.filter(Boolean).join(' ')}
function nav(p:string){history.pushState({},'',p);dispatchEvent(new PopStateEvent('popstate'))}
function getToken(){return localStorage.getItem('rm_session')||''}
async function api<T>(url:string,init:RequestInit={}):Promise<T>{const res=await fetch(url,{...init,headers:{'Content-Type':'application/json',...(getToken()?{Authorization:`Bearer ${getToken()}`}:{})}});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||'Request failed');return body}

export default function AppV2(){
 const [path,setPath]=useState(location.pathname);const [user,setUser]=useState<User|null>(null);const [servers,setServers]=useState<ServerItem[]>([]);const [selectedId,setSelectedId]=useState('');const [loading,setLoading]=useState(true);const [side,setSide]=useState(false);const [collapsed,setCollapsed]=useState(false);const [serverMenu,setServerMenu]=useState(false);const [toast,setToast]=useState<Toast|null>(null)
 const selected=servers.find(s=>s.id===selectedId)||servers[0]
 useEffect(()=>{const fn=()=>setPath(location.pathname);addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[])
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),2800);return()=>clearTimeout(t)},[toast])
 async function load(){if(!getToken()){setLoading(false);return}try{const d=await api<{user:User;servers:ServerItem[]}>('/api/auth/me');setUser(d.user);setServers(d.servers||[]);setSelectedId(p=>d.servers?.some(s=>s.id===p)?p:(d.servers?.[0]?.id||''))}catch{localStorage.removeItem('rm_session');setUser(null)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 if(path.startsWith('/verify/'))return <Verify />
 if(path==='/login')return <Login onDone={(u,s)=>{setUser(u);setServers(s);setSelectedId(s[0]?.id||'');nav('/dashboard')}}/>
 if(loading)return <div className="splash"><span className="brand-mark big">RM</span><span className="loader"/>Connecting to RM...</div>
 if(!user)return <Landing />
 const id=path.startsWith('/dashboard/')?path.split('/')[2]:'overview';const active=mods.find(m=>m.id===id)||mods[0]
 async function save(module:string,settings:Record<string,unknown>,enabled=true){if(!selected)return;try{await api('/api/dashboard/action',{method:'POST',body:JSON.stringify({action:'set_module',data:{server_id:selected.id,module,settings,enabled}})});setToast({kind:'success',message:'Saved to RM and ready for VPS sync'})}catch(e){setToast({kind:'error',message:e instanceof Error?e.message:'Save failed'})}}
 async function task(action:string,extra:Record<string,unknown>={}){if(!selected)return;try{await api('/api/dashboard/action',{method:'POST',body:JSON.stringify({action,data:{...extra,server_id:selected.id}})});setToast({kind:'success',message:'Task queued for the VPS bot'})}catch(e){setToast({kind:'error',message:e instanceof Error?e.message:'Action failed'})}}
 async function logout(){try{await api('/api/auth/logout',{method:'POST'})}catch{}localStorage.removeItem('rm_session');setUser(null);nav('/')}
 return <div className="app-shell">
  <aside className={cn('sidebar',collapsed&&'collapsed',side&&'mobile-open')}><div className="brand-row"><button className="brand" onClick={()=>nav('/')}><span className="brand-mark">RM</span>{!collapsed&&<b>RM</b>}</button><button className="collapse" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'›':'‹'}</button></div><div className="sidebar-scroll">{['Control','Protection','Management','Community','Access','Customization'].map(g=><div key={g}><div className="side-caption">{g}</div>{mods.filter(m=>m.group===g).map(m=>{const I=m.icon;return <button className={cn('side-link',active.id===m.id&&'active')} key={m.id} onClick={()=>{nav('/dashboard/'+m.id);setSide(false)}}><I size={17}/>{!collapsed&&<span>{m.label}</span>}{!collapsed&&m.id==='security'&&<em>LIVE</em>}</button>})}</div>)}</div><div className="sidebar-bottom"><div className="profile"><span className="avatar"><UserRound size={16}/></span>{!collapsed&&<span><b>{user.username}</b><small>{user.discord_username}</small></span>}</div><button className="side-link" onClick={logout}><LogOut size={17}/>{!collapsed&&<span>Log out</span>}</button></div></aside>
  {side&&<div className="mobile-overlay" onClick={()=>setSide(false)}/>}<section className="workspace"><header className="topbar"><button className="mobile-menu" onClick={()=>setSide(true)}><Menu size={20}/></button><div className="server-wrap"><button className="server-selector" onClick={()=>setServerMenu(v=>!v)}><span className="server-avatar">{selected?.icon||'RM'}</span><span><small>MANAGING</small><b>{selected?.name||'No owned server'}</b></span><ChevronDown size={15}/></button>{serverMenu&&<div className="server-menu">{servers.length?servers.map(s=><button key={s.id} onClick={()=>{setSelectedId(s.id);setServerMenu(false);setToast({kind:'success',message:'Switched to '+s.name})}}><span className="server-avatar">{s.icon}</span><span><b>{s.name}</b><small>{s.members.toLocaleString()} members · Owner</small></span><span className={cn('status-dot',s.online?'online':'offline')}/></button>):<div className="empty-server">No owned servers synced yet.</div>}</div>}</div><div className="top-spacer"/><button className="search-trigger" onClick={()=>setToast({kind:'info',message:'Use the sidebar to jump between modules'})}><Search size={15}/>Search settings<kbd>⌘ K</kbd></button><button className="icon-button"><Bell size={18}/></button><button className="icon-button" onClick={()=>nav('/dashboard/bot-settings')}><Settings size={18}/></button><span className="top-avatar">{user.username[0]?.toUpperCase()}</span></header>
  <main className="content">{!selected?<NoServers/>:<><div className="page-heading"><div><span className="eyebrow">RM CONTROL CENTER <i className="live-dot"/> CONNECTED</span><h1>{active.label}</h1><p>{active.description} · {selected.name}</p></div><div className="heading-actions"><button className="secondary-button" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="primary-button" onClick={()=>save(active.id,{updated_at:new Date().toISOString()})}><Check size={15}/>Save</button></div></div><Page id={active.id} selected={selected} save={save} task={task} toast={setToast}/></>}</main></section>{toast&&<div className={cn('toast',toast.kind)}><span>{toast.kind==='success'?<Check size={16}/>:toast.kind==='error'?<X size={16}/>:<Activity size={16}/>}</span>{toast.message}<button onClick={()=>setToast(null)}><X size={13}/></button></div>}</div>
}

function NoServers(){return <div className="empty-panel"><span className="empty-icon"><Server size={24}/></span><h2>No owned servers yet</h2><p>Start RM on your VPS with the same BOT_SYNC_KEY configured in Vercel, then run <code>rm!verify</code> inside the Discord server you own.</p><button className="primary-button" onClick={()=>nav('/login')}>Back to sign in</button></div>}
function Login({onDone}:{onDone:(u:User,s:ServerItem[])=>void}){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await api<{token:string}>('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});localStorage.setItem('rm_session',d.token);const me=await api<{user:User;servers:ServerItem[]}>('/api/auth/me');onDone(me.user,me.servers||[])}catch(e){setError(e instanceof Error?e.message:'Login failed')}finally{setBusy(false)}}return <div className="auth-shell"><div className="auth-card"><button className="brand auth-brand" onClick={()=>nav('/')}><span className="brand-mark">RM</span><b>RM</b></button><span className="eyebrow">RM ACCESS</span><h1>Welcome back.</h1><p>Sign in to manage the Discord servers you own.</p><form onSubmit={submit}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" placeholder="your-rm-name" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" placeholder="••••••••" required/></label>{error&&<div className="form-error"><AlertTriangle size={15}/>{error}</div>}<button className="primary-button full" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowRight size={16}/></button></form><div className="auth-note"><ShieldCheck size={14}/> New accounts come from <b>rm!verify</b> in a server you own.</div></div></div>}
function Verify(){const token=location.pathname.split('/')[2]||'';const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(password!==confirm)return setError('Passwords do not match');setBusy(true);try{const d=await api<{token:string}>('/api/public/verify/complete',{method:'POST',body:JSON.stringify({token,username,password})});localStorage.setItem('rm_session',d.token);nav('/dashboard')}catch(e){setError(e instanceof Error?e.message:'Verification failed')}finally{setBusy(false)}}return <div className="auth-shell"><div className="auth-card"><button className="brand auth-brand" onClick={()=>nav('/')}><span className="brand-mark">RM</span><b>RM</b></button><span className="eyebrow">ONE-TIME VERIFICATION</span><h1>Claim your RM dashboard.</h1><p>Create the username and password for your server control center.</p><form onSubmit={submit}><label>Dashboard username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="3–24 characters" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" required/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password" required/></label>{error&&<div className="form-error"><AlertTriangle size={15}/>{error}</div>}<button className="primary-button full" disabled={busy}>{busy?'Creating account…':'Finish verification'}<ShieldCheck size={16}/></button></form><div className="auth-note"><Lock size={14}/> This verification link is single-use and expires automatically.</div></div></div>}

function Page({id,selected,save,task,toast}:{id:string;selected:ServerItem;save:(m:string,s:Record<string,unknown>,e?:boolean)=>void;task:(a:string,d?:Record<string,unknown>)=>void;toast:(t:Toast)=>void}){
 if(id==='overview')return <Overview selected={selected} task={task}/>
 if(id==='appearance')return <Appearance save={save}/>
 if(id==='server-config')return <ServerConfig save={save}/>
 if(id==='automod')return <AutoMod save={save}/>
 if(id==='anti-raid')return <AntiRaid save={save} task={task}/>
 if(id==='anti-nuke')return <AntiNuke save={save}/>
 if(id==='welcome')return <Welcome save={save}/>
 if(id==='logs')return <Logs save={save}/>
 if(id==='wordfilter')return <WordFilter selected={selected} toast={toast} task={task}/>
 if(id==='custom-commands')return <CustomCommands selected={selected} toast={toast}/>
 return <Generic id={id} save={save} task={task}/>
}
function Switch({on,set}:{on:boolean;set:(v:boolean)=>void}){return <button className={cn('switch',on&&'on')} onClick={()=>set(!on)}><span/></button>}
function Row({title,desc,on,set}:{title:string;desc:string;on:boolean;set:(v:boolean)=>void}){return <div className="setting-row"><div><b>{title}</b><small>{desc}</small></div><Switch on={on} set={set}/></div>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder?:string}){return <label className="field"><span>{label}</span><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>}
function Save({on}:{on:()=>void}){return <div className="save-bar"><span><Check size={13}/>Ready to sync</span><button className="primary-button" onClick={on}>Save module</button></div>}
function Overview({selected,task}:{selected:ServerItem;task:(a:string,d?:Record<string,unknown>)=>void}){return <><div className="metric-grid">{[['Members',selected.members.toLocaleString(),Users],['Channels',String(selected.channels),Globe2],['Roles',String(selected.roles),KeyRound],['Bot',selected.online?'ONLINE':'OFFLINE',Activity]].map(([a,b,I])=><div className="metric-card" key={String(a)}><div className="metric-top"><span>{String(a)}</span><span className="metric-icon"><I size={16}/></span></div><strong>{String(b)}</strong><small>{a==='Bot'?'VPS bridge':'owned server'}</small></div>)}</div><div className="panel hero-panel"><div><span className="panel-kicker">SERVER CONTROL</span><h3>{selected.name}</h3><p>RM is connected through the shared BOT_SYNC_KEY bridge. Settings are stored server-side; the key never reaches your browser.</p><div className="hero-actions"><button className="primary-button" onClick={()=>task('reload_config')}><RefreshCw size={15}/>Reload config</button><button className="secondary-button" onClick={()=>task('raidmode_on')}><ShieldAlert size={15}/>Emergency raid mode</button><button className="danger-button" onClick={()=>task('lockdown')}><Lock size={15}/>Lockdown</button></div></div><div className="connection"><span><Activity size={19}/></span><b>{selected.online?'Live connection':'Offline'}</b><small>Discord owner access</small></div></div><div className="feature-grid">{[['AutoMod','automod','Message firewall',ShieldCheck],['Anti-Raid','anti-raid','Join defense',Radar],['Anti-Nuke','anti-nuke','Server integrity',ShieldAlert],['Tickets','tickets','Support routing',Ticket],['Welcome','welcome','Onboarding',Sparkles],['Custom Commands','custom-commands','Build rm! commands',Command]].map(([a,id,desc,I])=><button className="feature-card" key={String(id)} onClick={()=>nav('/dashboard/'+id)}><span className="feature-icon"><I size={18}/></span><span><b>{String(a)}</b><small>{String(desc)}</small></span><ArrowRight size={15}/></button>)}</div><div className="panel status-board"><div className="panel-head"><div><span className="panel-kicker">SECURITY POSTURE</span><h3>Core layers</h3></div><span className="status-chip safe"><ShieldCheck size={12}/>HEALTHY</span></div><div className="status-columns">{['AutoMod','Anti-Raid','Anti-Nuke','Logging','Tickets','Welcome'].map(x=><div key={x}><Check size={14}/><span>{x}</span><small>ready</small></div>)}</div></div></>}
function Generic({id,save,task}:{id:string;save:(m:string,s:Record<string,unknown>,e?:boolean)=>void;task:(a:string,d?:Record<string,unknown>)=>void}){const mod=mods.find(m=>m.id===id)||mods[0];const [enabled,setEnabled]=useState(true);const [strict,setStrict]=useState(true);const [logging,setLogging]=useState(true);const [threshold,setThreshold]=useState('5');return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">CORE CONTROL</span><h3>{mod.label}</h3></div><mod.icon size={18}/></div><Row title={`${mod.label} enabled`} desc="Master switch for this module." on={enabled} set={setEnabled}/><Row title="Strict mode" desc="Prefer safer automated actions." on={strict} set={setStrict}/><Row title="Audit logging" desc="Record actions in the RM pipeline." on={logging} set={setLogging}/></div><div className="panel"><div className="panel-head"><div><span className="panel-kicker">ADVANCED</span><h3>Fine tuning</h3></div><Settings size={18}/></div><Field label="Threshold" value={threshold} set={setThreshold}/><div className="mini-info"><ShieldCheck size={15}/>Changes are stored in server_settings and read by the VPS.</div><div className="hero-actions"><button className="secondary-button" onClick={()=>task('reload_config')}><RefreshCw size={15}/>Reload bot</button><Save on={()=>save(id,{strict,logging,threshold},enabled)}/></div></div></div>}
function AutoMod({save}:{save:(m:string,s:Record<string,unknown>,e?:boolean)=>void}){const [enabled,setEnabled]=useState(true),[spam,setSpam]=useState(true),[links,setLinks]=useState(true),[mentions,setMentions]=useState(true),[action,setAction]=useState('delete');return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">MESSAGE FIREWALL</span><h3>Rules</h3></div><ShieldCheck size={18}/></div><Row title="AutoMod" desc="Enable the message protection layer." on={enabled} set={setEnabled}/><Row title="Spam / flood" desc="Catch rapid posting bursts." on={spam} set={setSpam}/><Row title="Link protection" desc="Protect against suspicious links." on={links} set={setLinks}/><Row title="Mass mentions" desc="Detect mention abuse." on={mentions} set={setMentions}/></div><div className="panel"><div className="panel-head"><div><span className="panel-kicker">ACTION POLICY</span><h3>Default response</h3></div><Lock size={18}/></div><label className="field"><span>When a rule fires</span><select value={action} onChange={e=>setAction(e.target.value)}><option value="delete">Delete</option><option value="warn">Delete + warn</option><option value="timeout">Delete + timeout</option><option value="log">Log only</option></select></label><div className="mini-info"><Zap size={15}/>Individual rules can override the default.</div><Save on={()=>save('automod',{modules:{spam:{enabled:spam},links:{enabled:links},mention_spam:{enabled:mentions}},action},enabled)}/></div></div>}
function AntiRaid({save,task}:{save:(m:string,s:Record<string,unknown>,e?:boolean)=>void;task:(a:string,d?:Record<string,unknown>)=>void}){const [enabled,setEnabled]=useState(true),[joins,setJoins]=useState('8'),[windowSec,setWindowSec]=useState('10'),[age,setAge]=useState('7');return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">JOIN DEFENSE</span><h3>Raid thresholds</h3></div><Radar size={18}/></div><Row title="Anti-Raid" desc="Monitor join velocity." on={enabled} set={setEnabled}/><div className="field-row"><Field label="Joins" value={joins} set={setJoins}/><Field label="Window seconds" value={windowSec} set={setWindowSec}/></div><Field label="Minimum account age days" value={age} set={setAge}/></div><div className="panel"><div className="panel-head"><div><span className="panel-kicker">EMERGENCY</span><h3>Raid mode</h3></div><ShieldAlert size={18}/></div><div className="danger-card"><b>Force stricter screening</b><small>These actions are queued directly for the VPS bot.</small><div className="hero-actions"><button className="secondary-button" onClick={()=>task('raidmode_on')}><ShieldAlert size={15}/>Enable</button><button className="secondary-button" onClick={()=>task('raidmode_off')}><ShieldCheck size={15}/>Disable</button></div></div><Save on={()=>save('antiraid',{join_threshold:Number(joins),join_window_seconds:Number(windowSec),min_account_age_days:Number(age),action:'kick'},enabled)}/></div></div>}
function AntiNuke({save}:{save:(m:string,s:Record<string,unknown>,e?:boolean)=>void}){const all=['channel_delete','channel_create','role_delete','role_create','role_update','webhook_create','ban','kick'];const [enabled,setEnabled]=useState(true),[watch,setWatch]=useState(all.slice(0,5));return <div className="panel"><div className="panel-head"><div><span className="panel-kicker">SERVER INTEGRITY</span><h3>Watchlist</h3></div><ShieldAlert size={18}/></div><Row title="Anti-Nuke" desc="Protect high-impact Discord actions." on={enabled} set={setEnabled}/><div className="chip-grid">{all.map(x=><button className={cn('choice-chip',watch.includes(x)&&'selected')} key={x} onClick={()=>setWatch(v=>v.includes(x)?v.filter(a=>a!==x):[...v,x])}>{watch.includes(x)?<Check size={13}/>:<Plus size={13}/>} {x.replaceAll('_',' ')}</button>)}</div><Save on={()=>save('antinuke',{watch:Object.fromEntries(all.map(x=>[x,{enabled:watch.includes(x)}])),punishment:'ban'},enabled)}/></div>}
function Appearance({save}:{save:(m:string,s:Record<string,unknown>,e?:boolean)=>void}){const [accent,setAccent]=useState('#e11d48'),[glass,setGlass]=useState(true),[compact,setCompact]=useState(false),[brand,setBrand]=useState('RM');return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">BRAND SYSTEM</span><h3>Make RM yours</h3></div><Palette size={18}/></div><Field label="Brand name" value={brand} set={setBrand}/><label className="field"><span>Accent color</span><div className="color-row"><input type="color" value={accent} onChange={e=>setAccent(e.target.value)}/><input value={accent} onChange={e=>setAccent(e.target.value)}/></div></label><Row title="Glass interface" desc="Use translucent panels and layered surfaces." on={glass} set={setGlass}/><Row title="Compact layout" desc="Reduce spacing for smaller screens." on={compact} set={setCompact}/></div><div className="panel preview-panel"><span className="panel-kicker">LIVE PREVIEW</span><div className="brand-preview"><span className="brand-mark" style={{background:accent}}>{brand.slice(0,2).toUpperCase()}</span><div><b>{brand} Control Center</b><small>Server security, redesigned.</small></div></div><div className="preview-card" style={{borderColor:accent+'66'}}><span style={{color:accent}}>Security posture</span><strong>Excellent protection</strong><small>Core layers online · 0 critical alerts</small></div><Save on={()=>save('appearance',{accent,glass,compact,brand_name:brand},true)}/></div></div>}
function ServerConfig({save}:{save:(m:string,s:Record<string,unknown>,e?:boolean)=>void}){const [p,setP]=useState('rm!'),[alt,setAlt]=useState('rm?'),[lang,setLang]=useState('en');return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">COMMAND SYSTEM</span><h3>Prefixes</h3></div><Command size={18}/></div><div className="field-row"><Field label="Primary" value={p} set={setP}/><Field label="Secondary" value={alt} set={setAlt}/></div><label className="field"><span>Language</span><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">English</option><option value="ar">Arabic</option><option value="ku">Kurdish</option></select></label><Save on={()=>save('core',{prefixes:[p,alt].filter(Boolean),language:lang})}/></div><div className="panel"><div className="mini-info"><Check size={15}/>Prefix changes are read by RM's existing config loader and apply on the next refresh.</div><div className="command-preview"><span>Try</span><code>{p}help</code><span>or</span><code>{alt}help</code></div></div></div>}
function Logs({save}:{save:(m:string,s:Record<string,unknown>,e?:boolean)=>void}){const [enabled,setEnabled]=useState(true),[security,setSecurity]=useState(true),[moderation,setModeration]=useState(true),[channel,setChannel]=useState('');return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">AUDIT PIPELINE</span><h3>Logging</h3></div><FileText size={18}/></div><Row title="Logging" desc="Store RM actions and system events." on={enabled} set={setEnabled}/><Row title="Security events" desc="Anti-nuke and anti-raid alerts." on={security} set={setSecurity}/><Row title="Moderation cases" desc="Warnings, kicks, bans and timeouts." on={moderation} set={setModeration}/></div><div className="panel"><Field label="Security channel ID" value={channel} set={setChannel} placeholder="123456789012345678"/><div className="mini-info"><ShieldCheck size={15}/>The bot already sends security events through the sync bridge.</div><Save on={()=>save('logging',{channels:{security:channel},security,moderation},enabled)}/></div></div>}
function Welcome({save}:{save:(m:string,s:Record<string,unknown>,e?:boolean)=>void}){const [enabled,setEnabled]=useState(true),[channel,setChannel]=useState(''),[message,setMessage]=useState('Welcome {user} to {server}!');return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">ONBOARDING</span><h3>Welcome</h3></div><Sparkles size={18}/></div><Row title="Welcome module" desc="Send an automated join message." on={enabled} set={setEnabled}/><Field label="Channel ID" value={channel} set={setChannel}/><label className="field"><span>Message</span><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={5}/></label><Save on={()=>save('welcome',{channel_id:channel,message},enabled)}/></div><div className="panel"><span className="panel-kicker">PREVIEW</span><div className="welcome-preview"><span className="avatar big">RM</span><div><b>{message.replace('{user}','@NewMember').replace('{server}','Your Server')}</b><small>Sent by RM · just now</small></div></div></div></div>}
async function addWord(serverId:string,word:string){return api('/api/dashboard/action',{method:'POST',body:JSON.stringify({action:'add_blocked_word',data:{server_id:serverId,word}})})}
function WordFilter({selected,toast,task}:{selected:ServerItem;toast:(t:Toast)=>void;task:(a:string,d?:Record<string,unknown>)=>void}){const [word,setWord]=useState('');const [items,setItems]=useState<string[]>([]);async function add(){if(!word.trim())return;try{await addWord(selected.id,word.trim());setItems(v=>[...v,word.trim()]);setWord('');toast({kind:'success',message:'Blocked word added'})}catch(e){toast({kind:'error',message:e instanceof Error?e.message:'Failed'})}}return <div className="panel"><div className="panel-head"><div><span className="panel-kicker">CONTENT CONTROL</span><h3>Blocked words</h3></div><AlertTriangle size={18}/></div><div className="add-row"><input value={word} onChange={e=>setWord(e.target.value)} placeholder="word or phrase"/><button className="primary-button" onClick={add}><Plus size={15}/>Add</button></div><div className="chip-grid">{items.length?items.map((x,i)=><button className="choice-chip selected" key={i} onClick={()=>setItems(v=>v.filter((_,n)=>n!==i))}>{x}<X size={13}/></button>):<div className="muted-box">Add words here. Existing database rules remain untouched.</div>}</div><button className="secondary-button" onClick={()=>task('reload_config')}><RefreshCw size={15}/>Reload bot config</button></div>}
function CustomCommands({selected,toast}:{selected:ServerItem;toast:(t:Toast)=>void}){const [name,setName]=useState('hello'),[response,setResponse]=useState('Hey {user}, welcome to {server}!'),[items,setItems]=useState<string[]>([]);async function add(){try{await api('/api/dashboard/action',{method:'POST',body:JSON.stringify({action:'set_module',data:{server_id:selected.id,module:'custom_commands',settings:{commands:[...items,name],response_template:response},enabled:true}})});setItems(v=>[...v,name]);setName('');toast({kind:'success',message:'Custom command saved'})}catch(e){toast({kind:'error',message:e instanceof Error?e.message:'Save failed'})}}return <div className="two-col"><div className="panel"><div className="panel-head"><div><span className="panel-kicker">COMMAND BUILDER</span><h3>New command</h3></div><Command size={18}/></div><Field label="Name" value={name} set={setName} placeholder="hello"/><label className="field"><span>Response</span><textarea value={response} onChange={e=>setResponse(e.target.value)} rows={6}/></label><div className="mini-info"><Command size={15}/>Uses the active prefix, so this will be <code>rm!{name||'hello'}</code>.</div><button className="primary-button" onClick={add}><Plus size={15}/>Create command</button></div><div className="panel"><div className="panel-head"><div><span className="panel-kicker">YOUR COMMANDS</span><h3>Custom set</h3></div><BotIcon/></div>{items.length?items.map(x=><div className="list-row" key={x}><span className="command-pill">rm!{x}</span><button className="icon-button"><Trash2 size={15}/></button></div>):<div className="muted-box">No custom commands yet.</div>}</div></div>}
function BotIcon(){return <Zap size={18}/>}
function Landing(){return <div className="landing"><header className="landing-nav"><button className="brand" onClick={()=>nav('/')}><span className="brand-mark">RM</span><b>RM</b></button><nav><button className="active">Control Center</button><button onClick={()=>nav('/login')}>Sign in</button></nav><button className="primary-button" onClick={()=>nav('/login')}>Open Dashboard <ArrowRight size={15}/></button></header><section className="landing-hero"><div className="landing-copy"><span className="eyebrow"><i className="live-dot"/> DISCORD SECURITY, REBUILT</span><h1>Control your server.<br/><span>Without the messy panel.</span></h1><p>Moderation, security, automation and customization in one clean dashboard connected straight to your VPS bot.</p><div className="hero-actions"><button className="primary-button" onClick={()=>nav('/login')}>Enter Control Center <ArrowRight size={16}/></button><button className="secondary-button" onClick={()=>nav('/login')}>How verification works</button></div><div className="trust-row"><span><ShieldCheck size={14}/> Owner-only access</span><span><Lock size={14}/> Key stays server-side</span><span><Zap size={14}/> Live VPS sync</span></div></div><div className="hero-window"><div className="window-head"><span/> <span/> <span/> <b>RM CONTROL CENTER</b></div><div className="mock-body"><div className="mock-side"><span className="brand-mark">RM</span>{[LayoutDashboard,ShieldCheck,Radar,Ticket,Palette,Settings].map((I,i)=><i key={i} className={i===1?'on':''}><I size={14}/></i>)}</div><div className="mock-main"><div className="mock-top"><div><small>MANAGING</small><b>My Discord Server</b></div><span className="status-chip safe"><Activity size={11}/>LIVE</span></div><div className="mock-stats">{['12,480','99.98%','1,284'].map((x,i)=><div key={x}><small>{['MEMBERS','UPTIME','ACTIONS'][i]}</small><strong>{x}</strong></div>)}</div><div className="mock-cards">{['Anti-Nuke','AutoMod','Anti-Raid','Tickets'].map(x=><div key={x}><ShieldCheck size={14}/><b>{x}</b><small>Protected</small></div>)}</div></div></div></div></section><footer>RM Control Center · BOT_SYNC_KEY is only used server-to-server.</footer></div>}
